### shamik_april_2
## To test forward pass

In [1]:
from matplotlib import pyplot as plt 
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.e ** -x)
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x) / np.sum(np.exp(x), axis=0)

#load dataset and print entry
dataset = np.loadtxt(fname="sample_shuff_train.txt")

X_train = dataset[0,:2]
Y_train = dataset[0,2:]
print X_train
print Y_train

[ 10.63071181   8.09246276]
[ 1.  0.]


In [2]:
#create weight matrix
n_input = int(2)
n_hidden = int(3)
n_output = int(2)
hidden_weights = np.random.rand(n_hidden,n_input)
output_weights = np.random.rand(n_output,n_hidden)
print "hidden layer weight matrix:\n",hidden_weights
print "output layer weight matrix:\n",output_weights

hidden layer weight matrix:
[[ 0.41867779  0.29294189]
 [ 0.36826227  0.71944929]
 [ 0.17273545  0.05498344]]
output layer weight matrix:
[[ 0.3977447   0.24860463  0.07104514]
 [ 0.4654203   0.01540456  0.47941204]]


In [3]:
input_vector = np.array(X_train, ndmin=2).T
output_vector = np.dot(hidden_weights, input_vector)
print "output of summed input of hidden layer:\n",output_vector
output_vector = sigmoid(output_vector)
print "activated output of hidden layer:\n",output_vector
output_vector = np.dot(output_weights, output_vector)
print "output of summed input to last layer:\n",output_vector
output_vector = softmax(output_vector)
print "activated output of last layer:\n",output_vector

output of summed input of hidden layer:
[[ 6.82146423]
 [ 9.73700662]
 [ 2.28125225]]
activated output of hidden layer:
[[ 0.99891106]
 [ 0.99994095]
 [ 0.90731241]]
output of summed input to last layer:
[[ 0.71036167]
 [ 0.91529363]]
activated output of last layer:
[[ 0.44894556]
 [ 0.55105444]]


In [4]:
expected = np.array(Y_train,ndmin=2).T
print expected
error = np.sum([(expected-output_vector)**2])/2
print error

[[ 1.]
 [ 0.]]
0.303660993202
