### shamik_april_2
## To test forward pass with bias

In [1]:
from matplotlib import pyplot as plt 
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.e ** -x)
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x) / np.sum(np.exp(x), axis=0)

#load dataset and print entry
dataset = np.loadtxt(
fname="sample_shuff_train.txt")

X_train = dataset[0,:2]
Y_train = dataset[0,2:]
print X_train
print Y_train

[ 10.42626086   6.81303272]
[ 1.  0.]


In [2]:
#create weight matrix
n_input = int(2)
n_hidden = int(3)
n_output = int(2)
hidden_weights = np.random.rand(n_hidden,n_input+1)
output_weights = np.random.rand(n_output,n_hidden+1)
print "hidden layer weight matrix:\n",hidden_weights
print "output layer weight matrix:\n",output_weights

hidden layer weight matrix:
[[ 0.83965453  0.26925491  0.0433967 ]
 [ 0.16015403  0.49404071  0.90862132]
 [ 0.20776575  0.76989533  0.06788894]]
output layer weight matrix:
[[ 0.12565146  0.10656284  0.85290476  0.83842329]
 [ 0.17224095  0.94745758  0.77014386  0.5058765 ]]


In [3]:
input_vector = np.append(X_train,1.0)
print "input vector added bias:\n",input_vector
input_vector = np.array(input_vector, ndmin=2).T
print "input vector transposed:\n",input_vector
output_vector = np.dot(hidden_weights, input_vector)
print "output of summed input of hidden layer:\n",output_vector
output_vector = sigmoid(output_vector)
print "activated output of hidden layer:\n",output_vector
output_vector = np.append(output_vector,1.0)
output_vector = np.array(output_vector, ndmin=2).T
print "bias added output of hidden layer:\n",output_vector
output_vector = np.dot(output_weights, output_vector)
print "output of summed input to last layer:\n",output_vector
output_vector = softmax(output_vector)
print "activated output of last layer:\n",output_vector

input vector added bias:
[ 10.42626086   6.81303272   1.        ]
input vector transposed:
[[ 10.42626086]
 [  6.81303272]
 [  1.        ]]
output of summed input of hidden layer:
[[ 10.63229635]
 [  5.94434449]
 [  7.47943089]]
activated output of hidden layer:
[[ 0.99997588]
 [ 0.99738623]
 [ 0.99943574]]
bias added output of hidden layer:
[[ 0.99997588]
 [ 0.99738623]
 [ 0.99943574]
 [ 1.        ]]
output of summed input to last layer:
[[ 1.92277954]
 [ 2.39280374]]
activated output of last layer:
[[ 0.38461052]
 [ 0.61538948]]


In [4]:
expected = np.array(Y_train,ndmin=2).T
print expected
print output_vector
error = np.sum([(expected-output_vector)**2])/2
print error

[[ 1.]
 [ 0.]]
[[ 0.38461052]
 [ 0.61538948]]
0.37870421762
